globals:
  - &output_properties
    name: {col: name}
    area:
      call:
        func: util.safe_int
        args: [ { col: area } ]
    source: {col: source}
    min_zoom: {col: min_zoom}
    mz_label_placement: {col: mz_label_placement}
    label_placement: {col: label_placement}
filters:
  - filter:
      place: continent
      name: true
    min_zoom: 1
    output:
      <<: *output_properties
      kind: continent
    table: osm
  - filter:
      place: archipelago
      name: true
    # Once more feature are polygons, it would be worthwhile to do
    # min_zoom: GREATEST(7, LEAST((zoom+6)::smallint, 15))
    # but for now, it's mostly middling data
    min_zoom: 15
    output:
      <<: *output_properties
      kind: archipelago
    table: osm
  - filter:
      place: island
      name: true
    min_zoom: { clamp: { min: 7, max: 15, value: { sum: [ { col: zoom }, 5.75 ] } } }
    output:
      <<: *output_properties
      kind: island
    table: osm
  - filter:
      place: islet
      name: true
    min_zoom: { clamp: { min: 15, max: 17, value: { sum: [ { col: zoom }, 3.5 ] } } }
    output:
      <<: *output_properties
      kind: islet
    table: osm
  - filter: {natural: cliff}
    min_zoom: 13
    output:
      <<: *output_properties
      kind: cliff
    table: osm
  - filter: {natural: arete}
    min_zoom: 13
    output:
      <<: *output_properties
      kind: arete
    table: osm
  - filter:
      natural: ridge
      name: true
    min_zoom: 13
    output:
      <<: *output_properties
      kind: ridge
    table: osm
  - filter:
      natural: valley
      name: true
    min_zoom: 13
    output:
      <<: *output_properties
      kind: valley
    table: osm

  # Natural Earth data should have a min_zoom column in the data, and we'll use
  # that curated value to provide min_zoom.
  - filter:
      meta.source: ne
    min_zoom: { col: min_zoom }
    output:
      <<: *output_properties
      kind: earth

  # OSMData data is just polygons with auto-generated IDs. It's not used at low
  # zooms, but if we want consistency, we should try to work out an area-based
  # correspondance with NE data above.
  - filter:
      meta.source: shp
    min_zoom: 0
    output:
      <<: *output_properties
      kind: earth
