global:
  - &output_properties
    name: {col: name}
    source: {col: source}
    admin_level: {col: admin_level}
    population: {col: population}
    country_capital:
      call:
        func: util.tag_str_to_bool
        args: [ { col: capital } ]
    region_capital:
      call:
        func: util.tag_str_to_bool
        args: [ { col: state_capital } ]
    mz_n_photos: {col: mz_n_photos}
    area:
      call:
        func: util.safe_int
        args: [ { col: area } ]
    min_zoom: {col: min_zoom}
    max_zoom: {col: max_zoom}
    is_landuse_aoi:
      call:
        func: util.true_or_none
        args: [ { col: is_landuse_aoi } ]

  - &ne_places_min_zoom
    lookup:
      key: { col: scalerank }
      op: '<='
      table:
        - [ 2, 0 ]
        - [ 3, 1 ]
        - [ 4, 2 ]
        - [ 5, 4 ]
        - [ 6, 6 ]
        - [ 7, 7 ]
        - [ 9, 9 ]
      default: 10

filters:
  - filter: {meta.source: wof}
    min_zoom: {col: min_zoom}
    output:
      <<: *output_properties
      kind: {col: placetype}
    table: wof
    extra_columns: [ min_zoom ]
  - filter: {name: true, place: country}
    # note: min_zoom needs to be smaller than any min_label in
    # ne_10m_admin_0_countries to make sure we're not dropping any by not being
    # included in the PostgreSQL index.
    min_zoom: 1
    output:
      <<: *output_properties
      kind: country
      __ne_min_zoom: {col: __ne_min_zoom}
      __ne_max_zoom: {col: __ne_max_zoom}
    table: osm
  - filter: {name: true, place: state}
    # note: min_zoom needs to be smaller than any min_label in
    # ne_10m_admin_1_states_provinces to make sure we're not dropping any by
    # not being included in the PostgreSQL index.
    min_zoom: 3
    output:
      <<: *output_properties
      kind: region
      kind_detail: state
      __ne_min_zoom: {col: __ne_min_zoom}
      __ne_max_zoom: {col: __ne_max_zoom}
    table: osm
  - filter: {name: true, place: province}
    # note: min_zoom needs to be smaller than any min_label in
    # ne_10m_admin_1_states_provinces to make sure we're not dropping any by
    # not being included in the PostgreSQL index.
    min_zoom: 3
    output:
      <<: *output_properties
      kind: region
      kind_detail: province
      __ne_min_zoom: {col: __ne_min_zoom}
      __ne_max_zoom: {col: __ne_max_zoom}
    table: osm
  - filter: {name: true, population: true, place: [city, town]}
    min_zoom: 8
    output:
      <<: *output_properties
      kind: locality
      kind_detail: {col: place}
    table: osm
  - filter: {name: true, place: [city, town]}
    min_zoom: 9
    output:
      <<: *output_properties
      kind: locality
      kind_detail: {col: place}
    table: osm
  - filter: {name: true, population: true, place: village}
    min_zoom: 11
    output:
      <<: *output_properties
      kind: locality
      kind_detail: village
    table: osm
  - filter: {name: true, place: village}
    min_zoom: 12
    output:
      <<: *output_properties
      kind: locality
      kind_detail: village
    table: osm
  - filter: {name: true, population: true, place: hamlet}
    min_zoom: 12
    output:
      <<: *output_properties
      kind: locality
      kind_detail: hamlet
    table: osm
  - filter: {name: true, place: [locality, hamlet]}
    min_zoom: 13
    output:
      <<: *output_properties
      kind: locality
      kind_detail: {col: place}
    table: osm
  - filter: {name: true, place: isolated_dwelling}
    min_zoom: 13
    output:
      <<: *output_properties
      kind: locality
      kind_detail: isolated_dwelling
    table: osm
  - filter: {name: true, place: farm}
    min_zoom: 13
    output:
      <<: *output_properties
      kind: locality
      kind_detail: farm
    table: osm

  - filter:
      scalerank: true
      featurecla: [Admin-0 region capital, Admin-0 capital alt, Admin-0 capital]
    min_zoom: *ne_places_min_zoom
    output:
      <<: *output_properties
      kind: locality
      country_capital: true
    table: ne
  - filter:
      scalerank: true
      featurecla: [Admin-1 capital, Admin-1 region capital]
    min_zoom: *ne_places_min_zoom
    output:
      <<: *output_properties
      kind: locality
      region_capital: true
    table: ne
  - filter: {featurecla: Populated place, scalerank: true}
    min_zoom: *ne_places_min_zoom
    output:
      <<: *output_properties
      kind: locality
    table: ne

  - filter:
      scalerank: true
      featurecla: [Historic place]
    min_zoom: *ne_places_min_zoom
    output:
      <<: *output_properties
      kind: locality
      kind_detail: hamlet
    table: ne
  - filter:
      scalerank: true
      featurecla: [Scientific station]
    min_zoom: *ne_places_min_zoom
    output:
      <<: *output_properties
      kind: locality
      kind_detail: scientific_station
    table: ne
