global:
  - &output_properties
    source: {col: source}
    min_zoom: {col: min_zoom}
    name: {col: name}
    ref: {col: ref}
    operator: {col: operator}
    type: {col: type}
    colour: {col: colour}
    network: {col: network}
    state: {col: state}
    symbol: {col: symbol}
    description: {col: description}
    distance: {col: distance}
    ascent: {col: ascent}
    descent: {col: descent}
    roundtrip: {col: roundtrip}
    route_name: {col: route_name}
    layer: {col: layer}
    service: {col: service}

filters:
  - filter:
      route: train
      service: [high_speed, long_distance, international]
    min_zoom: 5
    output:
      <<: *output_properties
      kind: {col: route}
  - filter: {route: train}
    min_zoom: 6
    output:
      <<: *output_properties
      kind: train
  - filter: {route: subway}
    min_zoom: 8
    output:
      <<: *output_properties
      kind: subway
  - filter:
      route: [light_rail, tram]
    min_zoom: 9
    output:
      <<: *output_properties
      kind: {col: route}
  - filter:
      route: [funicular, monorail]
    min_zoom: 12
    output:
      <<: *output_properties
      kind: {col: route}
  - filter:
      railway: [halt, stop, tram_stop]
    min_zoom: 13
    output:
      <<: *output_properties
      kind: {col: railway}
  - filter: {highway: platform}
    min_zoom: 17
    output:
      <<: *output_properties
      kind: bus_stop
  - filter: {public_transport: platform, rail: 'yes'}
    min_zoom: 15
    output:
      <<: *output_properties
      kind: platform
  - filter: {public_transport: platform, light_rail: 'yes'}
    min_zoom: 15
    output:
      <<: *output_properties
      kind: platform
  - filter: {public_transport: platform, bus: 'yes'}
    min_zoom: 17
    output:
      <<: *output_properties
      kind: bus_stop
  - filter: {public_transport: platform}
    min_zoom: 15
    output:
      <<: *output_properties
      kind: platform
  - filter: {public_transport: stop_area}
    min_zoom: 15
    output:
      <<: *output_properties
      kind: stop_area
  - filter:
      railway: [platform, station]
    min_zoom: 15
    output:
      <<: *output_properties
      kind: {col: railway}
  - filter: {site: stop_area}
    min_zoom: 15
    output:
      <<: *output_properties
      kind: stop_area
  - filter: {highway: bus_stop}
    min_zoom: 17
    output:
      <<: *output_properties
      kind: bus_stop
