name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.16.15"

      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      - name: Run build
        run: go build .

      - name: Run vet & lint
        run: |
          go vet .
          golint .

      - name: Run tests
        run: go test -v ./...
